spring:
  datasource:
    url: jdbc:tc:postgresql:latest:///
    username: user
    password: password
  flyway:
    enabled: true
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: wisestart
